name = "GenericLinearAlgebra"
uuid = "14197337-ba66-59df-a3e3-ca00e7dcff7a"
version = "0.3.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
libblastrampoline_jll = "8e850b90-86db-534c-a0d3-1478176c7d93"

[compat]
julia = "1.6"

[extras]
Quaternions = "94ee1d12-ae83-5a48-8b1c-48b8ff168ae0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Quaternions", "Test"]
